package students;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-16T08:38:20.022+02:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "SchoolServiceService",
        wsdlLocation = "http://localhost:8080/students-ejb/SchoolService?wsdl",
        targetNamespace = "http://students/")
public class SchoolServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://students/", "SchoolServiceService");
    public final static QName SchoolServicePort = new QName("http://students/", "SchoolServicePort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/students-ejb/SchoolService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SchoolServiceService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/students-ejb/SchoolService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SchoolServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SchoolServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchoolServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SchoolServiceService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SchoolServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SchoolServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns SchoolService
     */
    @WebEndpoint(name = "SchoolServicePort")
    public SchoolService getSchoolServicePort() {
        return super.getPort(SchoolServicePort, SchoolService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SchoolService
     */
    @WebEndpoint(name = "SchoolServicePort")
    public SchoolService getSchoolServicePort(WebServiceFeature... features) {
        return super.getPort(SchoolServicePort, SchoolService.class, features);
    }

}
